######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 5 00:29:51 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywidget.h
SOURCES += main.cpp mywidget.cpp
