######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 27 19:01:41 2014
######################################################################

TEMPLATE = app 
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

SOURCES +=  main.cpp\
            mainwindow.cpp\
            ledcube.cpp
HEADERS +=  mainwindow.h\
            ledcube.h
RESOURCES += ledcube.qrc
FORMS += ledcube.ui
